config/routes.rb
SpeakerMeterServer::Application.routes.draw do
  get "sessions/new"
  post "sessions/create"

  resources :users

  resources :speakers

  resources :venues
  
  match 'speakers/:id/voteup' => "speakers#voteup"
  match 'speakers/:id/votedown' => "speakers#votedown"
  match 'speakers/:id/clear' => "speakers#clear"
  match 'speakers/:id/rate' => "speakers#rate"

  get "agenda" => "agenda#index"

  get "breaks" => "speakers#breaks"

end

app/models/speaker.rb
class Speaker < ActiveRecord::Base
  LANGUAGES = ['English', 'Polish']
  attr_accessible :name
  attr_accessible :presentation
  attr_accessible :description
  attr_accessible :visible
  attr_accessible :bio
  attr_accessible :timeslot
  attr_accessible :time_slot_id
  attr_accessible :language
  attr_accessible :average_rating
  attr_accessible :venue
  attr_accessible :venue_id

  #validates_inclusion_of :venue, :in => VENUES, :allow_nil => true, :allow_blank => true
  validates_inclusion_of :language, :in => LANGUAGES, :allow_nil => false, :allow_blank => false
  validates_presence_of :name, :presentation, :description, :bio


  belongs_to :venue
  has_many :votes
  has_many :ratings, :after_add => :update_average_rating, :after_remove => :update_average_rating

  belongs_to :timeslot, :class_name => "TimeSlot", :foreign_key => "time_slot_id"

  def as_json(options = {})
    @votes_down = self.votes.where({:isup => false}).count
    @votes = self.votes.count
    @updated_at = self.votes.maximum(:created_at)
    @votes_up = @votes - @votes_down
    {
      :id => self.id,
      :name => self.name,
      :presentation => self.presentation,
      :votes_down => @votes_down,
      :votes_up => @votes_up,
      :last_voted => @updated_at,
      :start_time => self.start_time,
      :end_time => self.end_time, 
      :venue =>  self.venue.nil? ? nil : self.venue.name,
      :venue_id => self.venue.nil? ? nil : self.venue.id,
      :language => self.language,
      :bio => self.bio,
      :description => self.description,
      :average_rating => self.average_rating,
      :visible => self.visible
   }
  end

  def start_time
	@time_slot = TimeSlot.find_by_id(self.time_slot_id)
	if @time_slot
		return @time_slot.start_time 
	end
  end

  def end_time
	@time_slot = TimeSlot.find_by_id(self.time_slot_id)
	if @time_slot
		return @time_slot.end_time 
	end
  end

  def update_average_rating(review=nil)
    s = self.ratings.sum(:rating)
    c = self.ratings.count
    self.update_attribute(:average_rating, c == 0 ? 0.0 : s / c.to_f)
  end
end

app/controllers/speakers_controller.rb
class SpeakersController < ApplicationController
  before_filter :authorize, :only => [ :new, :edit, :destroy, :update, :clear ]
  # GET /speakers
  # GET /speakers.json
  def index
    @speakers = Speaker.where("venue_id <> 0").sort_by { |s| 
      s.name.split(" ").last
    }

    respond_to do |format|
      format.html # index.html.erb
      format.json do
          render json: @speakers.to_json({:only => ['id', 'name'] })
        end
    end
  end

  # GET /breaks
  # GET /breaks.json
  def breaks
    @speakers = Speaker.where("venue_id = 0")

    respond_to do |format|
      format.html do
        render template: "speakers/index"
      end
      format.json do
        render json: @speakers.to_json({:only => ['id', 'name'] })
      end
    end
  end

  # GET /speakers/1
  # GET /speakers/1.json
  def show
    @speaker = Speaker.find(params[:id])

    respond_to do |format|
      format.html
        @votes_down = Vote.where({:isup => false}).find_all_by_speaker_id(params[:id])
        @votes = Vote.find_all_by_speaker_id(params[:id])
        @votes_up = @votes - @votes_down
	@ratings = @speaker.ratings
        # show.html.erb
      format.json do
        render json: @speaker.to_json()
      end
    end
  end

  # GET /speakers/new
  # GET /speakers/new.json
  def new
    @speaker = Speaker.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @speaker }
    end
  end

  # GET /speakers/1/edit
  def edit
    @speaker = Speaker.find(params[:id])
  end

  # POST /speakers
  # POST /speakers.json
  def create
    @speaker = Speaker.new(params[:speaker])

    respond_to do |format|
      if @speaker.save
        format.html { redirect_to @speaker, notice: "Speaker #{@speaker.name} was successfully created." }
        format.json { render json: @speaker, status: :created, location: @speaker }
      else
        format.html { render action: "new" }
        format.json { render json: @speaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /speakers/1
  # PUT /speakers/1.json
  def update
    @speaker = Speaker.find(params[:id])

    respond_to do |format|
      if @speaker.update_attributes(params[:speaker])
        format.html { redirect_to @speaker, notice: "Speaker #{@speaker.name} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @speaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /speakers/1
  # DELETE /speakers/1.json
  def destroy
    @speaker = Speaker.find(params[:id])
    @speaker.destroy

    respond_to do |format|
      format.html { redirect_to speakers_url }
      format.json { head :no_content }
    end
  end

  def voteup
    set_cookie
    @vote = Vote.new
    @vote.isup = true
    @vote.speaker = Speaker.find(params[:id])
    @vote.uuid = cookies[:uuid].to_s
    @vote.save
    redirect_to speaker_path(params[:id])
  end

  def votedown
    set_cookie
    @vote = Vote.new
    @vote.isup = false
    @vote.speaker = Speaker.find(params[:id])
    @vote.uuid = cookies[:uuid].to_s
    @vote.save
    redirect_to speaker_path(params[:id])
  end

  def clear
    @speaker = Speaker.find(params[:id])
    @speaker.votes.delete_all()
    redirect_to speaker_path(params[:id])
  end

  def set_cookie
    if cookies[:uuid].nil?
       cookies[:uuid] = UUIDTools::UUID.random_create().to_s
    end
  end

  def authorize
    if session[:user_id].nil?
      redirect_to sessions_new_path
    end
  end

  def rate
	@speaker = Speaker.find(params[:id])
	if not @speaker.nil?
	  r = Rating.new(params[:rating])
	  @speaker.ratings.push(r)
	  @speaker.save
	end
	redirect_to speaker_path
  end
end

app/helpers/speakers_helper.rb
module SpeakersHelper
end

app/views/speakers/_form.html.erb
<%= form_for(@speaker) do |f| %>
  <% if @speaker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@speaker.errors.count, "error") %> prohibited this speaker from being saved:</h2>

      <ul>
      <% @speaker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :presentation %><br />
    <%= f.text_field :presentation %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :language %><br />
    <%= f.select :language, Speaker::LANGUAGES  %>
  </div>
 
    <div class="field">
      <%= f.label :time_slot_id %><br />
      <%= f.select :time_slot_id, options_for_select(TimeSlot.all.collect{ |t| [t, t.id] }, @speaker.time_slot_id) , :include_blank => false %>
    </div>


    <div class="field">
      <%= f.label :venue %><br />
      <%
	if not @speaker.venue.nil?
		@selected = @speaker.venue.id
	end
      %>
      <%= f.select :venue_id, options_for_select(Venue.all.collect { |v| [v.name, v.id]}.unshift(["Break", 0]), @selected ) %>
    </div>

   <div class="field">
      <%= f.label :visible%><br />
      <%= f.check_box :visible %>
    </div>

 <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/speakers/edit.html.erb
<h1>Editing speaker</h1>

<%= render 'form' %>

<%= link_to 'Show', @speaker %> |
<%= link_to 'Back', speakers_path %>

app/views/speakers/index.html.erb
<h1>Listing speakers</h1>

<table border='1'>
  <tr>
    <th></th>
    <th>Name</th>
    <th>Start</th>
    <th>End</th>
    <th>Presentation</th>
    <th>Venue</th>
    <th>Votes up</th>
    <th>Votes down</th>
    <th>Percent</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% counter=0 %>
<% @speakers.each do |speaker| %>
<% counter = counter+1 %>
  <tr>
    <td><%= counter %>
    <td><%= speaker.name %></td>
    <td><%= speaker.start_time.strftime("%H:%M") %></td>
    <td><%= speaker.end_time.strftime("%H:%M") %></td>
    <td><%= speaker.presentation %></td>
    <td><%= speaker.venue.name if speaker.venue != nil %></td>
    <td><%= speaker.votes.where({:isup => true}).count %></td>
    <td><%= speaker.votes.where({:isup => false}).count %></td>
    <td><% if speaker.votes.count > 0%>
	<%= number_to_human(100.0 * speaker.votes.where({:isup => true}).count / speaker.votes.count) %>
	<% else %>
	0
	<% end %>
    </td>
    <td><%= link_to 'Show', speaker %></td>
    <td><%= link_to 'Edit', edit_speaker_path(speaker) %></td>
    <td><%= link_to 'Destroy', speaker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Speaker', new_speaker_path %>

app/views/speakers/new.html.erb
<h1>New speaker</h1>

<%= render 'form' %>

<%= link_to 'Back', speakers_path %>

app/views/speakers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<table>
  <tr>
    <td>Name:</td>
    <td><%= @speaker.name %></td>
  </tr>
  <tr>
    <td>Bio:</td>
    <td><%= @speaker.bio %></td>
  </tr>
  <tr>
    <td>Presentation:</td>
    <td><%= @speaker.presentation %></td>
  </tr>
  <tr>
    <td>Descripton:</td>
    <td><%= @speaker.description %></td>
  </tr>
  <tr>
    <td>Total votes:</td>
    <td><%= @votes.count%></td>
  </tr>
  <tr>
    <td>Votes up:</td>
    <td><%= @votes_up.count%></td>
  </tr>
  <tr>
    <td>Votes down:</td>
    <td><%= @votes_down.count%></td>
  </tr>
  <tr>
    <td>Percent:</td>
    <td><% if @votes.count > 0 %>
        <%= number_to_human(100.0 * @votes_up.count / @votes.count ) %>
        <% else %>
        0
        <% end %>
    </td>
  </tr>
  <tr>
	<td>Ratings:</td>
	<td>
		<table>
  			<% @ratings.each do |r| %>
			<tr>
				<td><%= r.comment %>
				<td><%= r.rating %>
			</tr>
  			<% end %>
		</table>
	</td>
	
  </tr>

</table>
</p>

<%= link_to 'Clear', :controller => 'speakers', :action => 'clear', :id => @speaker  %> |
<%= link_to 'Edit', edit_speaker_path(@speaker) %> |
<%= link_to 'Back', speakers_path %>